containers: 
  name: nodejs-sts
  image: dangtong76/nodeapp
  containerPort: 8080
volum:
  name: data
  mountPath: /var/data
  volumeClaimTemplates:
  size: 30Gi
  mode: ReadWriteOnce
  scname: standard