apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.metadata.name }}
spec:
    type: LoadBalancer
    ports:
    - port: {{ .Values.spec.ports.port }}
      targetPort: {{ .Values.spec.ports.targetPort }}
    selector:
        app: nodejs-sfs