apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodejs-sfs
spec:
  selector:
    matchLabels:
      app: nodejs-sfs
  serviceName: nodejs-sfs
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-sfs
    spec:
      containers:
      - name: {{ .Values.spec.template.spec.containers.name }}
        image: {{ .Values.spec.template.spec.containers.image }}
        ports:
        - name: http
          containerPort: {{ .Values.spec.template.spec.containers.containerPort }}
        volumeMounts:
        - name: {{ .Values.spec.template.spec.containers.volumeMounts.name }}
          mountPath: {{ .Values.spec.template.spec.containers.volumeMounts.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.spec.volumeClaimTemplates.metadata.name }}
    spec:
      resources:
        requests:
          storage: {{ .Values.spec.volumeClaimTemplates.spec.resources.requests.storage }}
      accessModes:
      - {{ .Values.spec.volumeClaimTemplates.spec.accessModes }}
      storageClassName: {{ .Values.spec.volumeClaimTemplates.spec.storageClassName }}