apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.containers.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.containers.name }}
  serviceName: {{ .Values.containers.name }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.containers.name }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ default "dangtong76/nodejs" .Values.containers.image }}
        ports:
        - name: http
          containerPort: {{ default 8080 .Values.containers.containerPort }}
        volumeMounts:
        - name: {{ default "data" .Values.volum.name }}
          mountPath: {{ default "/var/data" .Values.volum.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ default "data" .Values.volum.name }}
    spec:
      resources:
        requests:
          storage: {{ default "20Gi" .Values.volum.size }}
      accessModes:
      - {{ default "ReadWriteOnce" .Values.volum.mode }}
      storageClassName: {{ default "standard" .Values.volum.scname }}